/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    private String currentAbsolutePath;
    public void init() {
        currentAbsolutePath = new File(".").getAbsolutePath();
    }

    @Test
    void getDiffIdenticalFiles() throws IOException {
        init();
        Differ classUnderTest = new Differ();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/json1";
        assertEquals(Differ.generate(pathToFile1, pathToFile1),
                "{\n"
                        + "    follow: false\n"
                        + "    host: hexlet.io\n"
                        + "    proxy: 123.234.53.22\n"
                        + "    timeout: 50\n"
                        + "}");
    }

    @Test
    void getDiffAddInSecondFile() throws IOException {
        init();
        Differ classUnderTest = new Differ();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/json1";
        String pathToFile2 = currentAbsolutePath + "/src/main/resources/json3";
        assertEquals(Differ.generate(pathToFile1, pathToFile2),
                "{\n"
                        + "    follow: false\n"
                        + "    host: hexlet.io\n"
                        + "    proxy: 123.234.53.22\n"
                        + "    timeout: 50\n"
                        + "  + verbose: true\n"
                        + "}");
    }

    @Test
    void getDiffOnAllDiff() throws IOException {
        init();
        Differ classUnderTest = new Differ();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/json1";
        String pathToFile2 = currentAbsolutePath + "/src/main/resources/json2";
        assertEquals(Differ.generate(pathToFile1, pathToFile2),
                "{\n"
                        + "  - follow: false\n"
                        + "    host: hexlet.io\n"
                        + "  - proxy: 123.234.53.22\n"
                        + "  - timeout: 50\n"
                        + "  + timeout: 20\n"
                        + "  + verbose: true\n"
                        + "}");
    }
}
