/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    private String currentAbsolutePath;
    public void init() {
        currentAbsolutePath = new File(".").getAbsolutePath();
    }

    @Test
    void getDiffIdenticalFilesJson() throws IOException, Exception {
        init();
        Differ classUnderTest = new Differ();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/json1.json";
        assertEquals(Differ.generate(pathToFile1, pathToFile1),
                "{\n"
                        + "    follow: false\n"
                        + "    host: hexlet.io\n"
                        + "    proxy: 123.234.53.22\n"
                        + "    timeout: 50\n"
                        + "}");
    }

    @Test
    void getDiffAddInSecondFileJson() throws IOException, Exception {
        init();
        Differ classUnderTest = new Differ();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/json1.json";
        String pathToFile2 = currentAbsolutePath + "/src/main/resources/json3.json";
        assertEquals(Differ.generate(pathToFile1, pathToFile2),
                "{\n"
                        + "    follow: false\n"
                        + "    host: hexlet.io\n"
                        + "    proxy: 123.234.53.22\n"
                        + "    timeout: 50\n"
                        + "  + verbose: true\n"
                        + "}");
    }

    @Test
    void getDiffOnAllDiffJson() throws IOException, Exception {
        init();
        Differ classUnderTest = new Differ();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/json1.json";
        String pathToFile2 = currentAbsolutePath + "/src/main/resources/json2.json";
        assertEquals(Differ.generate(pathToFile1, pathToFile2),
                "{\n"
                        + "  - follow: false\n"
                        + "    host: hexlet.io\n"
                        + "  - proxy: 123.234.53.22\n"
                        + "  - timeout: 50\n"
                        + "  + timeout: 20\n"
                        + "  + verbose: true\n"
                        + "}");
    }

    @Test
    void getDiffOnAllDiffYaml() throws IOException, Exception {
        init();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/yaml1.yaml";
        String pathToFile2 = currentAbsolutePath + "/src/main/resources/yaml2.yaml";
        assertEquals(Differ.generate(pathToFile1, pathToFile2),
                "{\n"
                        + "  - author: Charles R. Saunders\n"
                        + "  - language: English\n"
                        + "  + language: Russia\n"
                        + "  - pages: 224\n"
                        + "  + pages: 300\n"
                        + "    publication-year: 1981\n"
                        + "}");
    }

    @Test
    void getErrorDiffOnYamlIncorrectExtension() throws IOException, Exception {
        init();
        currentAbsolutePath = currentAbsolutePath.substring(0, currentAbsolutePath.length() - 1);
        String pathToFile1 = currentAbsolutePath + "/src/main/resources/yaml1.s";
        String pathToFile2 = currentAbsolutePath + "/src/main/resources/yaml2.y";
        try {
            Differ.generate(pathToFile1, pathToFile2);
        } catch (Exception ex) {
            assertEquals(ex.getMessage(), "Incorrect file extensions were entered.");
        }

    }
}
