name: build-test-style
on:
 push:
 pull_request:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      java-version: 19
      distribution: temurin
   - name: Setup Gradle
     uses: gradle/gradle-build-action@v2
     with:
      gradle-version: 8.3
   - name: Execute Gradle build
     run: ./gradlew build
   - name: Generate JaCoCo Badge
     uses: cicirello/jacoco-badge-generator@v2
     with:
      generate-branches-badge: true
      jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv